### PR TITLE
Delete poi rouet test

### PR DESCRIPTION
**Pull request by ali1373107**

### CODE REVIEW

**Review by TomStrong — CHANGES_REQUESTED** [review]
You should not be hard coding the IDs as they will never be the same between tests. I think the best way to fix this would be to move each of the tests into one file, ensure they run in a set order and share the ID of a POI created from one of the first test with the rest of the tests.

**Comment by TomStrong** [comment]
Also make sure you always merge 'main' into your own branch first and create your branch from an issue in GitHub

**Comment by FaizanAhmedSP707** [comment]
I think I will review this pull request after the changes have been made.

**Comment by TomStrong** [comment]
Oh I also noticed the spelling of 'rouet' should be 'route'

**Review by TomStrong — APPROVED** [review]
Good job

**Review by 5thaks07 — APPROVED** [review]
nice work mate

**Pull request merged**
