### PR TITLE
59 research using azure blob to store photos

### PR DESCRIPTION
**Pull request by TomStrong**
I have implemented the backend for image upload, delete and update image for POIs.

I have limited the file size to 2MB to ensure we don't accidentally incur huge costs on our server storage.

In the frontend, I have added a file upload to the POI creation.

To fully utilise this feature, the front end needs some work to view the images and update POIs with a new image.
The front end should limit file upload to jpegs. 

@5thaks07 can you implement the remaining front end parts?

### CODE REVIEW

**Comment by FaizanAhmedSP707** [comment]
@TomStrong  So what you're asking Shiv to do, is to have an input button inside the popup that is shown when a POI is clicked on, with a limit of 2MB on photos, along with the necessary error checking and whatnot to alert the user that their file is too big, yeah?

**Review by 5thaks07 — APPROVED** [review]
Nice Work

**Review by tomstrong64 — APPROVED** [review]
Nice work @5thaks07

**Comment by tomstrong64** [comment]
I'll resolve conflicts and merge

**Pull request merged**
