### PR TITLE
159 create standard header and footer

### PR DESCRIPTION
**Pull request by ali1373107**

### CODE REVIEW

**Review by TomStrong — APPROVED** [review]
Looks good, nice one!

**Review by 5thaks07 — CHANGES_REQUESTED** [review]
You need to include the footer to all the pages

**Review by 5thaks07 — APPROVED** [review]
Nice Work Mate

**Review by TomStrong — CHANGES_REQUESTED** [review]
Need to add footer to login and register pages, the privacy policy link can be removed from the login after this.

Need to add translations for all of the content of the footer

**Pull request merged**
